const DOM = {
	asideBtns: document.querySelectorAll('.aside-btn'),
	account: document.getElementById('account'),
	accountList: document.getElementById('account-list'),
	accountDatalist: document.getElementById('account-datalist'),
	accountsSection: document.getElementById('accounts-section'),
	commoditiesSection: document.getElementById('commodities-section'),
	commodityList: document.getElementById('commodity-list'),
	entry: document.getElementById('entry'),
	entryAccountName: document.getElementById('entry-account-name'),
	entryAccountComment: document.getElementById('entry-account-comment'),
	entryAccountCommodity: document.getElementById('entry-account-commodity'),
	entryCommodityName: document.getElementById('entry-commodity-name'),
	entryDelete: document.getElementById('entry-delete'),
	entryDeleteBtn: document.getElementById('entry-delete-btn'),
	entryError: document.getElementById('entry-error'),
	entryFieldsets: document.querySelectorAll('.entry-fieldset'),
	entryForm: document.getElementById('entry-form'),
	entryFieldsetBtns: document.querySelectorAll('.entry-fieldset-btn'),
	entryId: document.getElementById('entry-id'),
	entryNav: document.getElementById('entry-nav'),
	entryNavFieldsetBtns: document.querySelectorAll('#entry-nav .entry-fieldset-btn'),
	entryOpenDeleteBtn: document.getElementById('entry-open-delete-btn'),
	entrySubmit: document.getElementById('entry-submit'),
	entryTitle: document.getElementById('entry-title'),
	entryType: document.getElementById('entry-type'),
	login: document.getElementById('login'),
	loginError: document.getElementById('login-error'),
	logout: document.getElementById('logout'),
	sections: document.querySelectorAll('main section'),
	toggleModals: document.querySelectorAll('.toggle-modal'),
	transactionsSection: document.getElementById('transactions-section'),
	wrapper: document.getElementById('wrapper'),
}
