const DOM = {
	asideBtns: document.querySelectorAll('.aside-btn'),
	account: document.getElementById('account'),
	accountList: document.getElementById('account-list'),
	accountDatalist: document.getElementById('account-datalist'),
	payeeDatalist: document.getElementById('payee-datalist'),
	tagsDatalist: document.getElementById('tags-datalist'),
	linksDatalist: document.getElementById('links-datalist'),
	accounts: document.getElementById('accounts'),
	transactionAddBtn: document.getElementById('transaction-add-btn'),
	transactionModal: document.getElementById('transaction-modal'),
	transactionDelete: document.getElementById('transaction-delete'),
	transactionDeleteBtn: document.getElementById('transaction-delete-btn'),
	transactionError: document.getElementById('transaction-error'),
	transactionForm: document.getElementById('transaction-form'),
	transactionId: document.getElementById('transaction-id'),
	transactionOpenDeleteBtn: document.getElementById('transaction-open-delete-btn'),
	transactionSubmit: document.getElementById('transaction-submit'),
	transactionTitle: document.getElementById('transaction-title'),
	transactionDate: document.getElementById('transaction-date'),
	transactionFlag: document.getElementById('transaction-flag'),
	transactionPayee: document.getElementById('transaction-payee'),
	transactionNarration: document.getElementById('transaction-narration'),
	transactionTags: document.getElementById('transaction-tags'),
	transactionLinks: document.getElementById('transaction-links'),
	transactionAddPostingBtn: document.getElementById('transaction-add-posting-btn'),
	transactionPostings: document.getElementById('transaction-postings'),
	transactions: document.getElementById('transactions'),
	transactionList: document.getElementById('transaction-list'),
	loginForm: document.getElementById('login-form'),
	loginError: document.getElementById('login-error'),
	logout: document.getElementById('logout'),
	sections: document.querySelectorAll('main section'),
	toggleModals: document.querySelectorAll('.toggle-modal'),
	wrapper: document.getElementById('wrapper'),
}
