const DOM = {
	asideBtns: document.querySelectorAll('.aside-btn'),
	accountsSection: document.getElementById('accounts-section'),
	account: document.getElementById('account'),
	commoditiesSection: document.getElementById('commodities-section'),
	commodityList: document.getElementById('commodity-list'),
	entry: document.getElementById('entry'),
	entryError: document.getElementById('entry-error'),
	entryFieldsets: document.querySelectorAll('.entry-fieldset'),
	entryForm: document.getElementById('entry-form'),
	entryFieldsetBtns: document.querySelectorAll('.entry-fieldset-btn'),
	entryNavFieldsetBtns: document.querySelectorAll('#entry-nav .entry-fieldset-btn'),
	entrySubmit: document.getElementById('entry-submit'),
	entryTitle: document.getElementById('entry-title'),
	entryType: document.getElementById('entry-type'),
	login: document.getElementById('login'),
	loginError: document.getElementById('login-error'),
	logout: document.getElementById('logout'),
	sections: document.querySelectorAll('main section'),
	toggleModals: document.querySelectorAll('.toggle-modal'),
	transactionsSection: document.getElementById('transactions-section'),
	wrapper: document.getElementById('wrapper'),
}
